export const languages = [
    // { name: "Afrikaans", code: "afr" },
    // { name: "Akan", code: "aka" },
    // { name: "Albanian", code: "alb" },
    // { name: "Albanian (Albania)", code: "alb-AL" },
    // { name: "Albanian (Kosovo)", code: "alb-XK" },
    // { name: "Albanian (Macedonia)", code: "alb-MK" },
    // { name: "Albanian (Montenegro)", code: "alb-ME" },
    // { name: "Amharic", code: "amh" },
    // { name: "Apache, Western", code: "apw" },
    // { name: "Arabic", code: "ara" },
    // { name: "Arabic (Algeria)", code: "ara-DZ" },
    // { name: "Arabic (Bahrain)", code: "ara-BH" },
    // { name: "Arabic (Egypt)", code: "ara-EG" },
    // { name: "Arabic (Iraq)", code: "ara-IQ" },
    // { name: "Arabic (Jordan)", code: "ara-JO" },
    // { name: "Arabic (Kuwait)", code: "ara-KW" },
    // { name: "Arabic (Lebanon)", code: "ara-LB" },
    // { name: "Arabic (Libya)", code: "ara-LY" },
    // { name: "Arabic (Morocco)", code: "ara-MA" },
    // { name: "Arabic (Oman)", code: "ara-OM" },
    // { name: "Arabic (Qatar)", code: "ara-QA" },
    // { name: "Arabic (Saudi Arabia)", code: "ara-SA" },
    // { name: "Arabic (Syria)", code: "ara-SY" },
    // { name: "Arabic (Tunisia)", code: "ara-TN" },
    // { name: "Arabic (U.A.E.)", code: "ara-AE" },
    // { name: "Arabic (Yemen)", code: "ara-YE" },
    // { name: "Aragonese", code: "arg" },
    // { name: "Aranese", code: "ocs" },
    // { name: "Armenian", code: "hye" },
    // { name: "Assamese", code: "asm" },
    // { name: "Asturian", code: "ast" },
    // { name: "Atikamekw", code: "atj" },
    // { name: "Azeri (Cyrillic)", code: "azf" },
    // { name: "Azeri (Latin)", code: "aze" },
    // { name: "Babine-Witsuwit'en", code: "bcr" },
    // { name: "Bangala", code: "bxg" },
    // { name: "Basque", code: "baq" },
    // { name: "Belarussian", code: "bel" },
    // { name: "Bengali", code: "ben" },
    // { name: "Bengali (Bangladesh)", code: "ben-BD" },
    // { name: "Bengali (India)", code: "ben-IN" },
    // { name: "Bislama", code: "bis" },
    // { name: "Blackfoot", code: "bla" },
    // { name: "Bosnian (Cyrillic)", code: "boc" },
    // { name: "Bosnian (Latin)", code: "bos" },
    // { name: "Breton", code: "bre" },
    // { name: "Bulgarian", code: "bul" },
    // { name: "Burmese", code: "mya" },
    // { name: "Catalan", code: "cat" },
    // { name: "Cebuano", code: "ceb" },
    // { name: "Cherokee", code: "chr" },
    // { name: "Chin", code: "ctd" },
    // { name: "Chinese (Hong Kong S.A.R.)", code: "zho-HK" },
    // { name: "Chinese (Macao S.A.R.)", code: "zho-MO" },
    { name: "Chinese (PRC)", code: "zho-CN" },
    // { name: "Chinese (Singapore)", code: "zho-SG" },
    // { name: "Chinese (Taiwan)", code: "zho-TW" },
    // { name: "Choctaw", code: "cho" },
    // { name: "Chuukese", code: "chk" },
    // { name: "Cree (Latin)", code: "cre" },
    // { name: "Cree, Eastern (Syllabics)", code: "crk" },
    // { name: "Cree, Western (Syllabics)", code: "crl" },
    // { name: "Croatian", code: "hrv" },
    // { name: "Czech", code: "cze" },
    // { name: "Danish", code: "dan" },
    // { name: "Dari", code: "prs" },
    // { name: "Dene", code: "chp" },
    // { name: "Dinka", code: "din" },
    // { name: "Dogrib", code: "dgr" },
    // { name: "Dutch", code: "dut" },
    // { name: "Dutch (Belgium)", code: "dut-BE" },
    // { name: "Dutch (Netherlands)", code: "dut-NL" },
    { name: "English", code: "eng" },
    // { name: "English (Australia)", code: "eng-AU" },
    // { name: "English (Belize)", code: "eng-BZ" },
    // { name: "English (Canada)", code: "eng-CA" },
    // { name: "English (Caribbean)", code: "eng-CB" },
    // { name: "English (Ireland)", code: "eng-IE" },
    // { name: "English (Jamaica)", code: "eng-JM" },
    // { name: "English (New Zealand)", code: "eng-NZ" },
    // { name: "English (Republic of the Philippines)", code: "eng-PH" },
    // { name: "English (South Africa)", code: "eng-ZA" },
    // { name: "English (Trinidad and Tobago)", code: "eng-TT" },
    // { name: "English (United Kingdom)", code: "eng-GB" },
    // { name: "English (United States)", code: "eng-US" },
    // { name: "English (Zimbabwe)", code: "eng-ZW" },
    // { name: "Esperanto", code: "epo" },
    // { name: "Estonian", code: "est" },
    // { name: "Fanti", code: "fat" },
    // { name: "Farsi", code: "fas" },
    // { name: "Fijian", code: "fij" },
    // { name: "Filipino", code: "fil" },
    // { name: "Finnish", code: "fin" },
    // { name: "Flemish", code: "vls" },
    // { name: "French", code: "fre" },
    // { name: "French (Africa)", code: "fre-02" },
    // { name: "French (Belgium)", code: "fre-BE" },
    // { name: "French (Canada)", code: "fre-CA" },
    // { name: "French (France)", code: "fre-FR" },
    // { name: "French (Luxembourg)", code: "fre-LU" },
    // { name: "French (Monaco)", code: "fre-MC" },
    // { name: "French (Morocco)", code: "fre-MA" },
    // { name: "French (Switzerland)", code: "fre-CH" },
    // { name: "Frisian, Western", code: "fry" },
    // { name: "Fulah", code: "ful" },
    // { name: "Gaelic (Scotland)", code: "gla" },
    // { name: "Galician", code: "glg" },
    // { name: "Georgian", code: "kat" },
    // { name: "German", code: "ger" },
    // { name: "German (Austria)", code: "ger-AT" },
    // { name: "German (Germany)", code: "ger-DE" },
    // { name: "German (Liechtenstein)", code: "ger-LI" },
    // { name: "German (Luxembourg)", code: "ger-LU" },
    // { name: "German (Switzerland)", code: "ger-CH" },
    // { name: "Greek", code: "gre" },
    // { name: "Greenlandic", code: "kal" },
    // { name: "Guaraní", code: "grn" },
    // { name: "Gujarati", code: "guj" },
    // { name: "Haitian Creole", code: "hat" },
    // { name: "Hausa", code: "hau" },
    // { name: "Hawaiian", code: "haw" },
    // { name: "Hazaragi", code: "haz" },
    // { name: "Hebrew", code: "heb" },
    // { name: "Hiligaynon", code: "hil" },
    // { name: "Hindi", code: "hin" },
    // { name: "Hmong", code: "hmn" },
    // { name: "Hopi", code: "hop" },
    // { name: "Hungarian", code: "hun" },
    // { name: "Icelandic", code: "ice" },
    // { name: "Igbo", code: "ibo" },
    // { name: "Ilocano", code: "ilo" },
    // { name: "Indonesian", code: "ind" },
    // { name: "Innu", code: "moe" },
    // { name: "Inuktitut, Eastern (Latin)", code: "ike" },
    // { name: "Inuktitut, Eastern (Syllabics)", code: "ikf" },
    // { name: "Inuktitut, Western (Latin)", code: "ikt" },
    // { name: "Inuktitut, Western (Syllabics)", code: "ikg" },
    // { name: "Irish", code: "gle" },
    // { name: "Italian", code: "ita" },
    // { name: "Italian (Italy)", code: "ita-IT" },
    // { name: "Italian (Switzerland)", code: "ita-CH" },
    // { name: "Japanese", code: "jpn" },
    // { name: "Javanese", code: "jav" },
    // { name: "Kabuverdianu", code: "kea" },
    // { name: "Kannada", code: "kan" },
    // { name: "Karen", code: "ksw", note: "Target language only" },
    // { name: "Kashmiri", code: "kas" },
    // { name: "Kayah (Latin)", code: "kyu", alternativeNames: "Karenni" },
    // { name: "Kayah (Myanmar)", code: "eky", alternativeNames: "Karenni", note: "Target language only" },
    // { name: "Kazakh", code: "kaz" },
    // { name: "Khmer", code: "khm", note: "Target language only" },
    // { name: "Kiribati", code: "gil" },
    // { name: "Klingon", code: "qqq" },
    // { name: "Korean", code: "kor" },
    // { name: "Kurdish (Arabic)", code: "ckb" },
    // { name: "Kurdish (Cyrillic)", code: "kmr" },
    // { name: "Kurdish (Latin)", code: "kur" },
    // { name: "Kyrgyz (Cyrillic)", code: "kir" },
    // { name: "Lao", code: "lao", note: "Target language only" },
    // { name: "Latin", code: "lat" },
    // { name: "Latvian", code: "lav" },
    // { name: "Lingala", code: "lin" },
    // { name: "Lithuanian", code: "lit" },
    // { name: "Luxembourgish", code: "ltz" },
    // { name: "Maay", code: "ymm" },
    // { name: "Macedonian", code: "mac" },
    // { name: "Malagasy", code: "mlg" },
    // { name: "Malay", code: "msa" },
    // { name: "Malayalam", code: "mal" },
    // { name: "Maltese", code: "mlt" },
    // { name: "Mandinka (Arabic)", code: "mno" },
    // { name: "Mandinka (Latin)", code: "mnk" },
    // { name: "Maori", code: "mri" },
    // { name: "Marathi", code: "mar" },
    // { name: "Marshallese", code: "mah" },
    // { name: "Meänkieli", code: "fit" },
    // { name: "Mi'kmaq", code: "mic" },
    // { name: "Michif", code: "crg", alternativeNames: "French Cree" },
    // { name: "Mohawk", code: "moh", alternativeNames: "Kanienkehaka" },
    // { name: "Moldavian", code: "mol" },
    // { name: "Mon", code: "mnw", note: "Target language only" },
    // { name: "Mongolian (Cyrillic)", code: "khk" },
    // { name: "Montenegrin (Cyrillic)", code: "cgy" },
    // { name: "Montenegrin (Latin)", code: "cgl" },
    // { name: "Nauruan", code: "nau" },
    // { name: "Navajo", code: "nav" },
    // { name: "Nepali", code: "nep" },
    // { name: "Norwegian", code: "nor" },
    // { name: "Norwegian (Bokmål)", code: "nnb" },
    // { name: "Norwegian (Nynorsk)", code: "nno" },
    // { name: "Occitan", code: "oci", alternativeNames: "oc-FR" },
    // { name: "Ojibwa (Latin)", code: "oji" },
    // { name: "Ojibwa (Syllabics)", code: "ojg" },
    // { name: "Oriya", code: "ori" },
    // { name: "Oromo", code: "orm", alternativeNames: "om-ET" },
    // { name: "Pashto", code: "pbu" },
    // { name: "Pennsylvania German", code: "pdc" },
    // { name: "Plautdietsch", code: "pdt", alternativeNames: "Mennonite German; Mennoniten Platt" },
    // { name: "Pijin", code: "pis" },
    // { name: "Pohnpeian", code: "pon" },
    // { name: "Polish", code: "pol" },
    // { name: "Portuguese", code: "por" },
    // { name: "Portuguese (Brazil)", code: "por-BR", alternativeNames: "pt-br" },
    // { name: "Portuguese (Portugal)", code: "por-PT", alternativeNames: "pt-pt" },
    // { name: "Punjabi (Gurmukhi)", code: "pan" },
    // { name: "Punjabi (Shahmukhi)", code: "pnb", alternativeNames: "pa-Arab" },
    // { name: "Quechua", code: "quz", alternativeNames: "quz-BO" },
    // { name: "Rakhine", code: "rki", note: "Target language only" },
    // { name: "Rohingya", code: "rhg" },
    // { name: "Romanian", code: "rum" },
    // { name: "Rundi", code: "run" },
    { name: "Russian", code: "rus" },
    // { name: "Rwanda", code: "kin", alternativeNames: "rw-RW" },
    // { name: "Samoan", code: "smo" },
    // { name: "Sanskrit", code: "san" },
    // { name: "Serbian (Cyrillic)", code: "scc" },
    // { name: "Serbian (Latin)", code: "scr" },
    // { name: "Sesotho", code: "sot" },
    // { name: "Shan", code: "shn", note: "Target language only" },
    // { name: "Sinhala", code: "sin" },
    // { name: "Slovak", code: "slo" },
    // { name: "Slovenian", code: "slv" },
    // { name: "Somali", code: "som" },
    // { name: "Somali (Djibouti)", code: "som-DJ" },
    // { name: "Somali (Ethiopia)", code: "som-ET" },
    // { name: "Somali (Kenya)", code: "som-KE" },
    // { name: "Somali (Somalia)", code: "som-SO" },
    // { name: "Spanish", code: "spa" },
    // { name: "Spanish (Argentina)", code: "spa-AR", alternativeNames: "es-ar" },
    // { name: "Spanish (Bolivia)", code: "spa-BO", alternativeNames: "es-bo" },
    // { name: "Spanish (Chile)", code: "spa-CL", alternativeNames: "es-cl" },
    // { name: "Spanish (Colombia)", code: "spa-CO", alternativeNames: "es-co" },
    // { name: "Spanish (Costa Rica)", code: "spa-CR", alternativeNames: "es-cr" },
    // { name: "Spanish (Dominican Republic)", code: "spa-DO", alternativeNames: "es-do" },
    // { name: "Spanish (Ecuador)", code: "spa-EC", alternativeNames: "es-ec" },
    // { name: "Spanish (El Salvador)", code: "spa-SV", alternativeNames: "es-sv" },
    // { name: "Spanish (Guatemala)", code: "spa-GT", alternativeNames: "es-gt" },
    // { name: "Spanish (Honduras)", code: "spa-HN", alternativeNames: "es-hn" },
    { name: "Spanish (Latin America)", code: "spa-M9", alternativeNames: "x-es-XL" },
    // { name: "Spanish (Mexico)", code: "spa-MX", alternativeNames: "es-mx" },
    // { name: "Spanish (Nicaragua)", code: "spa-NI", alternativeNames: "es-ni" },
    // { name: "Spanish (Panama)", code: "spa-PA", alternativeNames: "es-pa" },
    // { name: "Spanish (Paraguay)", code: "spa-PY", alternativeNames: "es-py" },
    // { name: "Spanish (Peru)", code: "spa-PE", alternativeNames: "es-pe" },
    // { name: "Spanish (Puerto Rico)", code: "spa-PR", alternativeNames: "es-pr" },
    // { name: "Spanish (Spain)", code: "spa-ES", alternativeNames: "es-es" },
    // { name: "Spanish (United States)", code: "spa-US", alternativeNames: "es-us" },
    // { name: "Spanish (Uruguay)", code: "spa-UY", alternativeNames: "es-uy" },
    // { name: "Spanish (Venezuela)", code: "spa-VE", alternativeNames: "es-ve" },
    // { name: "Stoney", code: "sto", alternativeNames: "Nakoda" },
    // { name: "Sudanese Creole Arabic", code: "pga" },
    // { name: "Sundanese", code: "sun" },
    // { name: "Swahili", code: "swa" },
    // { name: "Swedish", code: "swe" },
    // { name: "Swedish (Finland)", code: "swe-FI", alternativeNames: "sv-fi" },
    // { name: "Swedish (Sweden)", code: "swe-SE", alternativeNames: "sv-se" },
    // { name: "Tagalog", code: "tgl" },
    // { name: "Tajiki (Cyrillic)", code: "tgk", alternativeNames: "tg-Cyrl" },
    // { name: "Tamazight", code: "tzm", alternativeNames: "tzm-Latn" },
    // { name: "Tamil", code: "tam" },
    // { name: "Tatar", code: "tat", alternativeNames: "tt-RU" },
    // { name: "Telugu", code: "tel" },
    // { name: "Tetun Dili", code: "tdt" },
    // { name: "Thai", code: "tha" },
    // { name: "Tigrigna", code: "tir", alternativeNames: "ti-ET", note: "Target language only" },
    // { name: "Tok Pisin", code: "tpi" },
    // { name: "Tongan", code: "ton" },
    // { name: "Torres Strait Creole", code: "tcs" },
    // { name: "Tswana", code: "tsn", alternativeNames: "tn-BW" },
    // { name: "Turkish", code: "tur" },
    // { name: "Turkmen (Latin)", code: "tuk" },
    // { name: "Tuvaluan", code: "tvl" },
    // { name: "Twi", code: "twi" },
    // { name: "Ukrainian", code: "ukr" },
    // { name: "Urdu", code: "urd" },
    // { name: "Uzbek (Cyrillic)", code: "uzn" },
    // { name: "Uzbek (Latin)", code: "uzb", alternativeNames: "uz-Latn-UZ" },
    // { name: "Vietnamese", code: "vie" },
    // { name: "Welsh", code: "wel" },
    // { name: "Wolof", code: "wol", alternativeNames: "wo-SN" },
    // { name: "Xhosa", code: "xho" },
    // { name: "Yiddish", code: "yid" },
    // { name: "Yoruba", code: "yor" },
    // { name: "Zulu", code: "zul" }
];
